configMapGenerator:
- files:
  - application.yml
  name: cloud-sample-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ceappacr.azurecr.io/82023201
  newTag: "202410210735"
